trigger:
  batch: true
  branches:
    include:
      - "*"
    exclude:
      - azdevops/*

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  path: repos/github-repo
  workspaceRepo: true

- checkout: git://$(System.TeamProject)/powerplatform-sdk-extensions
  path: repos/azdevops-repo
  workspaceRepo: false
